import type { Metadata } from 'next'
import { SocketProvider } from '@/providers/socket-provider'
import '../globals.css'
import Bubbles from '@/components/custom/Background/Bubbles/Bubbles'

export const metadata: Metadata = {
  title: 'blindtest.kaitems.fr',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <SocketProvider>
        <body className='h-screen bg-gradient-to-t from-primary-50 to-primary-200'>
          <Bubbles opacity={0.2} />
          {children}
        </body>
      </SocketProvider>
    </html>
  )
}
