import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'blindtest.kaitems.fr',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='h-screen bg-gradient-to-t from-primary-50 to-primary-200'>{children}</body>
    </html>
  )
}